services:
  jellyseerr:
    image: ghcr.io/fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=critical
      - TZ=${TIMEZONE}
    volumes:
      - ./jellyseerr:/app/config
    restart: always
    networks:
      - media
    ports:
      - 5055:5055

  overseerr:
    image: linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=critical
      - TZ=${TIMEZONE}
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - UMASK=002
    volumes:
      - ./overseerr/config:/app/config
    ports:
      - 5056:5055
    restart: always
    networks:
      - media

  bazarr:
    image: lscr.io/linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
    volumes:
      - ./bazarr/config:/config
      - ${DATA_ROOT}/movies:/movies
      - ${DATA_ROOT}/tv:/tv
    restart: always
    networks:
      - media
    ports:
      - 6767:6767

  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
    volumes:
      - ./radarr:/config
      - ${DATA_ROOT}/movies:/data
      - ${DOWNLOADS}:/downloads   # SABnzb/qbit
    restart: always
    ports:
      - 7878:7878
    networks:
      - media

  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr-tv
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
    volumes:
      - ./sonarr/config:/config
      - ${DATA_ROOT}/tv:/data
      - ${DOWNLOADS}:/downloads   # SABnzb/qbit
    restart: always
    networks:
      - media
    ports:
      - 8989:8989

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - TZ=${TIMEZONE}
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
    volumes:
      - ./config:/config
      - ${DOWNLOADS}:/downloads
      - ${DOWNLOADS}/.incomplete:/incomplete-downloads
    ports:
      - 8090:8080
    restart: unless-stopped
    networks:
      - media

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:5.0.4 # fixed version
    container_name: qbittorrent
    env_file:
      - .env
    environment:
      - TZ=${TIMEZONE}
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - WEBUI_PORT=8080
      - TORRENTING_PORT=51000
      - WEBUI_USERNAME=${WEBUI_USERNAME}
      - WEBUI_PASSWORD=${WEBUI_PASSWORD}
    volumes:
      - ./appdata:/config
      - ${DOWNLOADS}:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 51000:51000/udp
    restart: unless-stopped
    networks:
      - media

networks:
  media:
    external: true
